baseURL = 'https://kd8bny.com/'
languageCode = 'en-us'

# Allow search engine indexing
enableRobotsTXT = true

theme = 'terminal'
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
pagination.pagerSize = 5

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
noClasses = false

[params]
# dir name of your main content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 3

# show selector to switch language
showLanguageSelector = false

# set theme to full screen width
fullWidthTheme = true

# center theme with default width
centerTheme = true

# if your resource directory contains an image called `cover.(jpg|png|webp)`,
# then the file will be used as a cover automatically.
# With this option you don't have to put the `cover` param in a front-matter.
autoCover = true

# set post to show the last updated
# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
showLastUpdated = false

# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
# updatedDatePrefix = "Updated"

# whether to show a page's estimated reading time
readingTime = true #false default

# whether to show a table of contents
# can be overridden in a page's front-matter
Toc = false # default

# set title for the table of contents
# can be overridden in a page's front-matter
#TocTitle = "Table of Contents" # default

# Set date/time format for posts
# This will impact the date/time displayed on
# index.html, the posts list page, and on posts themselves
# This value can also be configured per-post on front matter
# If you have any issues with the timezone rendering differently
# than you expected, please ensure your timezone is correctly set
# on your server.
# This value can be customized according to Hugo documentation:
# https://gohugo.io/functions/time/format/
# Default value (no changes needed):
# dateFormat = "2006-01-02"
# Example format, with date, time, and timezone abbreviation:
# dateFormat = "2006-01-02 3:04:06 PM MST"


[languages]
[languages.en]
languageName = "English"
title = "~/kd8bny"

[languages.en.params]
subtitle = "A blog about things and stuff"
owner = "daryl - kd8bny"
keywords = ""
copyright = "2025 Daryl Bennett All rights reserved"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[Author]
name = "Daryl Bennett"
email = "blog@kd8bny.com"

[markup.goldmark.renderer]
unsafe = true

[languages.en.params.logo]
logoText = "~/kd8bny"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "blog"
name = "blog"
url = "/posts"
weight = 10
[[languages.en.menu.main]]
identifier = "Bar"
name = "the_bar"
url = "/bar"
weight = 20
[[languages.en.menu.main]]
identifier = "whoami"
name = "whoami"
url = "/whoami"
weight = 30
[[languages.en.menu.main]]
identifier = "tags"
name = "tags"
url = "/tags"
[[languages.en.menu.main]]
identifier = "rss"
name = "RSS"
url = "https://kd8bny.com/index.xml"

[params.giscus]
repo = "kd8bny/blog"
repoID = "R_kgDOGzJrfg"
category = "Comments"
categoryID = "DIC_kwDOGzJrfs4CP2TM"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "dark"
lang = "en"
loading = "lazy"

# [module]
#  # In case you would like to make changes to the theme and keep it locally in you repository,
#  # uncomment the line below (and correct the local path if necessary).
#  # --
#  # replacements = "github.com/panr/hugo-theme-terminal/v4 -> themes/terminal"
# [[module.imports]]
# path = 'github.com/panr/hugo-theme-terminal/v4'
